### ISSUE TITLE
Unable to run COSMO without Dockerfile

### ISSUE THREAD

**Issue by annapamma** [bzhanglab/COSMO#1]
Hello! I am attempting to run COSMO as directed in the README.

I was able to install all of the prerequisite software and run `nextflow cosmo.nf --help` successfully. However, when I attempt to run the sample command with the example data:

```
nextflow run cosmo.nf --pro_file example_data/for_2b/Testing_1/test_pro.tsv \
>     --rna_file example_data/for_2b/Testing_1/test_rna.tsv \
>     --cli_file  example_data/for_2b/Testing_1/test_cli.tsv \
>     --cli_attribute "gender,msi" \
>     --out_dir output

```

I received the following error:

```
Command error:
  Unable to find image 'cosmo:latest' locally
```

I did not see a Dockerfile in the repository, and I was not sure where to pull this `cosmo` Docker image. 

Do you have the Dockerfile available so I can build the image, or is there a remote repository that I can pull the image from?

Thank you!

**Comment by wenbostar** [comment]
Hi Anna,

The Dockerfile file is in this branch: https://github.com/bzhanglab/COSMO/tree/docker. The docker will be available at the Docker hub shortly.

**Comment by wenbostar** [comment]
The docker is now available at Docker hub and you don't need to install that manually.
