### ISSUE TITLE
Update docker container with new Dockerfile

### ISSUE THREAD

**Issue by toddcreasy** [bzhanglab/COSMO#8]
Hi,

The last PR merges have created and made changes to the Dockerfile. I need to build the container from the Dockerfile we added to replace the “proteomics/cosmo:latest” container to include the new updates. Can someone take care of this for me?

Thanks,

-todd

**Comment by zhiaos** [comment]
Hi,

The image has been rebuilt with new tag "bzhanglab/cosmo:lastest"

Zhiao

**Comment by toddcreasy** [comment]
Thanks for doing this so quickly. Unfortunately, it looks like changes to the Dockerfile might have introduced an error (see below). Do you think this is related?

`Error executing process > 'METHOD2'

Caused by:
  Essential container in task exited

Command executed:

  method2_function.py \
      -d1 test_rna.tsv \
      -d2 test_pro.tsv \
      -s test_cli.tsv \
      -l gender,msi \
      -o method2_out

Command exit status:
  1

Command output:
  Processing file: test_rna.tsv and test_pro.tsv

Command error:
  Processing file: test_rna.tsv and test_pro.tsv
  Traceback (most recent call last):
    File "//nextflow-bin/method2_function.py", line 255, in <module>
      main()
    File "//nextflow-bin/method2_function.py", line 252, in main
      run(d1_file=d1_file, d2_file=d2_file, sample_file=sample_file, sample_labels=sample_label, out_dir=out_dir)
    File "//nextflow-bin/method2_function.py", line 117, in run
      upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))
    File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 284, in __getattr__
      raise AttributeError("module {!r} has no attribute "
  AttributeError: module 'numpy' has no attribute 'bool'
`

**Comment by zhiaos** [comment]
It's related to the newer numpy version in the docker image.  I've updated the code.  Please try again.

**Comment by toddcreasy** [comment]
@zhiaos - Sorry but I ran into another error. Any ideas on this one?

Error executing process > 'METHOD2'

Caused by:
  Essential container in task exited

Command executed:

  method2_function.py \
      -d1 test_pro.tsv \
      -d2 test_rna.tsv \
      -s test_cli.tsv \
      -l gender,msi \
      -o method2_out

Command exit status:
  1

Command output:
  Processing file: test_pro.tsv and test_rna.tsv

Command error:
  Processing file: test_pro.tsv and test_rna.tsv
  Traceback (most recent call last):
    File "//nextflow-bin/method2_function.py", line 255, in <module>
      main()
    File "//nextflow-bin/method2_function.py", line 252, in main
      run(d1_file=d1_file, d2_file=d2_file, sample_file=sample_file, sample_labels=sample_label, out_dir=out_dir)
    File "//nextflow-bin/method2_function.py", line 132, in run
      ('feature_selection', GenericUnivariateSelect(f_classif, 'fdr', param=0.1)),
  TypeError: __init__() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given

**Comment by zhiaos** [comment]
looks like there are some changes in the latest version of sklearn for GenericUnivariateSelect. I've updated the code.  Please try again.

**Comment by toddcreasy** [comment]
I forked the repo and did some more testing and I think the only thing that needs to be added to the Dockerfile is installing the docopt R package. Can you update that and then rebuild the image?

**Comment by zhiaos** [comment]
I think docopt is already available from the base image.

**Comment by toddcreasy** [comment]
Yes, you're right. Sorry about that! Thanks for all your help. Closing this.
